### PR TITLE
Spec for opcode `SAR`

### PR DESCRIPTION
**Pull request by silathdiir**
Merge new opcode `SAR` with `SHR`.

### CODE REVIEW

**Comment by lispc** [comment]
TODO: remove the SHR stuff here @LuozhuZhang

**Comment by LuozhuZhang** [comment]
> TODO: remove the SHR stuff here @LuozhuZhang

Remove the SHR from [SAR](https://github.com/scroll-tech/zkevm-specs/blob/feat/opcode-sar/specs/opcode/1dSAR.md)

**Comment by lispc** [comment]
@LuozhuZhang conflicts

**Comment by LuozhuZhang** [comment]
> @LuozhuZhang conflicts

merge

**Comment by silathdiir** [comment]
Already has been moved to upstream https://github.com/privacy-scaling-explorations/zkevm-specs/pull/263

**Pull request closed without merging**
